function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(4)=0;
    ys_(5)=0;
    ys_(6)=0;
    ys_(8)=0;
    ys_(9)=0;
    ys_(10)=0;
    ys_(11)=0;
    C_sum=0;
    ys_(12)=0;
    ys_(1)=1/sqrt(params(3));
    lambda_b=ys_(1)*params(3)/params(4);
    ys_(2)=ys_(1)*params(4);
    ys_(14)=(log(ys_(2))-params(3)/2*ys_(1)^2)/(1-params(5));
    ys_(15)=ys_(14);
    ys_(13)=(log(ys_(2))-params(3)/2*ys_(1)^2+ys_(15)*params(5)*7*(1-params(8))/params(9))/(1-params(5)*(1-7/params(9)));
    ys_(3)=params(5)*(ys_(14)-ys_(13));
    ys_(7)=params(10);
    ys_(16)=ys_(2);
    ys_(17)=0;
    c1_dev_4weeks=0;
    ys_(18)=ys_(2);
    ys_(19)=0;
    c2_dev_4weeks=0;
    ys_(20)=ys_(2);
    ys_(22)=1;
    ys_(21)=1;
    % Auxiliary equations
end
