%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'multisector';
M_.dynare_version = '4.6.1';
oo_.dynare_version = '4.6.1';
options_.dynare_version = '4.6.1';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('multisector.log');
M_.exo_names = cell(1,1);
M_.exo_names_tex = cell(1,1);
M_.exo_names_long = cell(1,1);
M_.exo_names(1) = {'eps'};
M_.exo_names_tex(1) = {'eps'};
M_.exo_names_long(1) = {'eps'};
M_.endo_names = cell(18,1);
M_.endo_names_tex = cell(18,1);
M_.endo_names_long = cell(18,1);
M_.endo_names(1) = {'n'};
M_.endo_names_tex(1) = {'n'};
M_.endo_names_long(1) = {'Labor supply'};
M_.endo_names(2) = {'c'};
M_.endo_names_tex(2) = {'c'};
M_.endo_names_long(2) = {'Agg. consumption'};
M_.endo_names(3) = {'lambda_tau'};
M_.endo_names_tex(3) = {'lambda\_tau'};
M_.endo_names_long(3) = {'Lambda'};
M_.endo_names(4) = {'tau'};
M_.endo_names_tex(4) = {'tau'};
M_.endo_names_long(4) = {'Probability of infection'};
M_.endo_names(5) = {'I'};
M_.endo_names_tex(5) = {'I'};
M_.endo_names_long(5) = {'Infected'};
M_.endo_names(6) = {'T'};
M_.endo_names_tex(6) = {'T'};
M_.endo_names_long(6) = {'Newly infected'};
M_.endo_names(7) = {'S'};
M_.endo_names_tex(7) = {'S'};
M_.endo_names_long(7) = {'Susceptible'};
M_.endo_names(8) = {'R'};
M_.endo_names_tex(8) = {'R'};
M_.endo_names_long(8) = {'Recovered'};
M_.endo_names(9) = {'D'};
M_.endo_names_tex(9) = {'D'};
M_.endo_names_long(9) = {'Deceased'};
M_.endo_names(10) = {'C'};
M_.endo_names_tex(10) = {'C'};
M_.endo_names_long(10) = {'Agg. consumption'};
M_.endo_names(11) = {'N'};
M_.endo_names_tex(11) = {'N'};
M_.endo_names_long(11) = {'Agg. labor'};
M_.endo_names(12) = {'Ui'};
M_.endo_names_tex(12) = {'Ui'};
M_.endo_names_long(12) = {'Lifetime utility of infected'};
M_.endo_names(13) = {'Us'};
M_.endo_names_tex(13) = {'Us'};
M_.endo_names_long(13) = {'Lifetime utility of susceptible'};
M_.endo_names(14) = {'Ur'};
M_.endo_names_tex(14) = {'Ur'};
M_.endo_names_long(14) = {'Lifetime utility of recovered'};
M_.endo_names(15) = {'c1'};
M_.endo_names_tex(15) = {'c1'};
M_.endo_names_long(15) = {'c1'};
M_.endo_names(16) = {'c1_dev'};
M_.endo_names_tex(16) = {'c1\_dev'};
M_.endo_names_long(16) = {'c1_dev'};
M_.endo_names(17) = {'c2'};
M_.endo_names_tex(17) = {'c2'};
M_.endo_names_long(17) = {'c2'};
M_.endo_names(18) = {'c2_dev'};
M_.endo_names_tex(18) = {'c2\_dev'};
M_.endo_names_long(18) = {'c2_dev'};
M_.endo_partitions = struct();
M_.param_names = cell(12,1);
M_.param_names_tex = cell(12,1);
M_.param_names_long = cell(12,1);
M_.param_names(1) = {'pi_s'};
M_.param_names_tex(1) = {'{\pi_s}'};
M_.param_names_long(1) = {'Probability of becoming infected'};
M_.param_names(2) = {'pi_a'};
M_.param_names_tex(2) = {'{\pi_a}'};
M_.param_names_long(2) = {'Probability of autonomous infection'};
M_.param_names(3) = {'pi_r'};
M_.param_names_tex(3) = {'{\pi_r}'};
M_.param_names_long(3) = {'Probability of recovery'};
M_.param_names(4) = {'pi_d'};
M_.param_names_tex(4) = {'{\pi_d}'};
M_.param_names_long(4) = {'Probability of death'};
M_.param_names(5) = {'eta'};
M_.param_names_tex(5) = {'{\eta}'};
M_.param_names_long(5) = {'Dlasticity of substitution'};
M_.param_names(6) = {'theta'};
M_.param_names_tex(6) = {'{\theta}'};
M_.param_names_long(6) = {'Labor supply parameter'};
M_.param_names(7) = {'A'};
M_.param_names_tex(7) = {'{A}'};
M_.param_names_long(7) = {'Productivity'};
M_.param_names(8) = {'betta'};
M_.param_names_tex(8) = {'{\beta}'};
M_.param_names_long(8) = {'Discount factor'};
M_.param_names(9) = {'phi1'};
M_.param_names_tex(9) = {'{\phi_{1}}'};
M_.param_names_long(9) = {'phi1'};
M_.param_names(10) = {'ups1'};
M_.param_names_tex(10) = {'{\upsilon_{1}}'};
M_.param_names_long(10) = {'ups1'};
M_.param_names(11) = {'phi2'};
M_.param_names_tex(11) = {'{\phi_{2}}'};
M_.param_names_long(11) = {'phi2'};
M_.param_names(12) = {'ups2'};
M_.param_names_tex(12) = {'{\upsilon_{2}}'};
M_.param_names_long(12) = {'ups2'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 1;
M_.endo_nbr = 18;
M_.param_nbr = 12;
M_.orig_endo_nbr = 18;
M_.aux_vars = [];
M_.Sigma_e = zeros(1, 1);
M_.Correlation_matrix = eye(1, 1);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.linear_decomposition = false;
M_.orig_eq_nbr = 18;
M_.eq_nbr = 18;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 6 0;
 0 7 0;
 0 8 0;
 0 9 0;
 1 10 0;
 2 11 0;
 3 12 0;
 4 13 0;
 5 14 0;
 0 15 0;
 0 16 0;
 0 17 24;
 0 18 25;
 0 19 26;
 0 20 0;
 0 21 0;
 0 22 0;
 0 23 0;]';
M_.nstatic = 10;
M_.nfwrd   = 3;
M_.npred   = 5;
M_.nboth   = 0;
M_.nsfwrd   = 3;
M_.nspred   = 5;
M_.ndynamic   = 8;
M_.dynamic_tmp_nbr = [9; 3; 0; 0; ];
M_.equations_tags = {
  1 , 'name' , 'FOC sector 1' ;
  2 , 'name' , 'c1_dev' ;
  3 , 'name' , 'FOC sector 2' ;
  4 , 'name' , 'c2_dev' ;
  5 , 'name' , '5' ;
  6 , 'name' , 'c' ;
  7 , 'name' , 'tau' ;
  8 , 'name' , 'lambda_tau' ;
  9 , 'name' , 'Ui' ;
  10 , 'name' , 'Ur' ;
  11 , 'name' , 'Us' ;
  12 , 'name' , 'T' ;
  13 , 'name' , '13' ;
  14 , 'name' , 'I' ;
  15 , 'name' , 'R' ;
  16 , 'name' , 'D' ;
  17 , 'name' , 'C' ;
  18 , 'name' , 'N' ;
};
M_.mapping.n.eqidx = [1 3 5 11 18 ];
M_.mapping.c.eqidx = [1 3 6 11 17 ];
M_.mapping.lambda_tau.eqidx = [1 3 8 ];
M_.mapping.tau.eqidx = [7 11 12 ];
M_.mapping.I.eqidx = [1 3 7 13 14 15 16 17 18 ];
M_.mapping.T.eqidx = [12 14 ];
M_.mapping.S.eqidx = [12 13 17 18 ];
M_.mapping.R.eqidx = [15 17 18 ];
M_.mapping.D.eqidx = [16 ];
M_.mapping.C.eqidx = [17 ];
M_.mapping.N.eqidx = [18 ];
M_.mapping.Ui.eqidx = [8 9 11 ];
M_.mapping.Us.eqidx = [8 11 ];
M_.mapping.Ur.eqidx = [9 10 ];
M_.mapping.c1.eqidx = [1 2 5 6 7 ];
M_.mapping.c1_dev.eqidx = [2 ];
M_.mapping.c2.eqidx = [3 4 5 6 7 ];
M_.mapping.c2_dev.eqidx = [4 ];
M_.mapping.eps.eqidx = [14 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [5 6 7 8 9 ];
M_.exo_names_orig_ord = [1:1];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(18, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(1, 1);
M_.params = NaN(12, 1);
M_.endo_trends = struct('deflator', cell(18, 1), 'log_deflator', cell(18, 1), 'growth_factor', cell(18, 1), 'log_growth_factor', cell(18, 1));
M_.NNZDerivatives = [65; -1; -1; ];
M_.static_tmp_nbr = [9; 3; 0; 0; ];
clc;
M_.params(5) = 10;
eta = M_.params(5);
M_.params(1) = 4.05e-07;
pi_s = M_.params(1);
M_.params(2) = 0;
pi_a = M_.params(2);
M_.params(4) = 0.001944444444444445;
pi_d = M_.params(4);
M_.params(3) = 0.3888888888888889-M_.params(4);
pi_r = M_.params(3);
M_.params(8) = 0.9992152697058329;
betta = M_.params(8);
M_.params(7) = 39.835;
A = M_.params(7);
M_.params(6) = 0.001275;
theta = M_.params(6);
M_.params(9) = 0.2;
phi1 = M_.params(9);
M_.params(10) = 0.5;
ups1 = M_.params(10);
M_.params(12) = 0.5;
ups2 = M_.params(12);
M_.params(11) = 2-M_.params(9);
phi2 = M_.params(11);
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',1,'multiplicative',0,'periods',1:1,'value',0.001) ];
M_.exo_det_length = 0;
options_.periods = 500;
perfect_foresight_setup;
clc;
M_.params(1) = 1e-09;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3e-09;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 5e-09;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 7e-09;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 9e-09;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.1e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.3e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.5e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.7e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.9e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.1e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.3e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.5e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.7e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.9e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.1e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.3e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.5e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.7e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.9e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 4.1e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 4.3e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 4.5e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 4.7e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 4.9e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 5.1e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 5.3e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 5.5e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 5.7e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 5.9e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 6.1e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 6.3e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 6.5e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 6.7e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 6.9e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 7.1e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 7.3e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 7.5e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 7.7e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 7.9e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 8.1e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 8.3e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 8.5e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 8.7e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 8.9e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 9.1e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 9.30000000000001e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 9.50000000000001e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 9.70000000000001e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 9.90000000000001e-08;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.01e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.03e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.05e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.07e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.09e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.11e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.13e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.15e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.17e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.19e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.21e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.23e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.25e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.27e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.29e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.31e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.33e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.35e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.37e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.39e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.41e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.43e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.45e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.47e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.49e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.51e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.53e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.55e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.57e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.59e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.61e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.63e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.65e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.67e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.69e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.71e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.73e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.75e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.77e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.79e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.81e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.83e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.85e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.87e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.89e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.91e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.93e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.95e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.97e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.99e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.01e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.03e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.05e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.07e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.09e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.11e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.13e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.15e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.17e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.19e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.21e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.23e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.25e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.27e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.29e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.31e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.33e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.35e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.37e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.39e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.41e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.43e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.45e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.47e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.49e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.51e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.53e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.55e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.57e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.59e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.61e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.63e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.65e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.67e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.69e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.71e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.72999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.74999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.76999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.78999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.80999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.82999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.84999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.86999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.88999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.90999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.92999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.94999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.96999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.98999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.00999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.02999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.04999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.06999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.08999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.10999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.12999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.14999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.16999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.18999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.20999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.22999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.24999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.26999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.28999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.30999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.32999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.34999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.36999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.38999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.40999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.42999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.44999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.46999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.48999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.50999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.52999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.54999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.56999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.58999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.60999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.62999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.64999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.66999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.68999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.70999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.72999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.74999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.76999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.78999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.80999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.82999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.84999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.86999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.88999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.90999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.92999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.94999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.96999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.98999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 4.00999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 4.02999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 4.04999999999999e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
varmat = [I S R D C N];
titles = {  'Infected', 'Susceptible', 'Recovered',...    
             'Deceased', 'Agg. cons.', 'Agg. labor'};
figure;
for x = 1:size(varmat,2)
subplot(2,3,x);
plot(0:150, 100.*varmat(2:152, x), 'color', [0 0 1], 'linewidth', 2);
title(titles{x});
if x > 3
xlabel('Weeks');
end
end
clean_current_folder;
save('multisector_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('multisector_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('multisector_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('multisector_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('multisector_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('multisector_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('multisector_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
